"""
Module: build_vector_db_new.py
Purpose: Build FAISS vector database from new chunk format with metadata
Input: Chunks from pipeline.py (with Context Hoisting and metadata)
Output: FAISS index + corpus_data.json (for RAG retrieval)
"""

import json
import sys
from pathlib import Path
import time
from typing import List, Dict, Any

try:
    import faiss
    import numpy as np
    from tqdm import tqdm
except ImportError:
    print("❌ Missing dependencies: faiss-cpu, numpy, tqdm")
    print("Install with: pip install faiss-cpu numpy tqdm")
    sys.exit(1)

# Add project to path
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from pipeline.embedding import get_embeddings


class VectorDatabaseBuilder:
    """Build FAISS vector database from processed chunks."""
    
    def __init__(self, output_dir: str = "vector_store"):
        """Initialize builder."""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
        self.indices_dir = self.output_dir / "indices"
        self.indices_dir.mkdir(exist_ok=True)
        
        self.faiss_index_path = self.output_dir / "faiss_index_new.bin"
        self.corpus_path = self.output_dir / "corpus_data_new.json"
        self.manifest_path = self.output_dir / "index_manifest_new.json"
        
        self.chunks: List[Dict[str, Any]] = []
        self.embeddings: np.ndarray = None
        self.faiss_index: faiss.Index = None
        self.corpus_entries: List[Dict[str, Any]] = []
    
    def load_chunks_from_pipeline(self, chunk_files: List[str]) -> bool:
        """
        Load chunks generated by pipeline.py
        
        Args:
            chunk_files: List of paths to chunk JSON files
        """
        try:
            print("\n[1/4] Loading chunks from pipeline output...")
            
            for file_path in chunk_files:
                path = Path(file_path)
                if not path.exists():
                    print(f"⚠ Skipping {path}: file not found")
                    continue
                
                with open(path, 'r', encoding='utf-8') as f:
                    chunks = json.load(f)
                
                self.chunks.extend(chunks)
                print(f"✓ Loaded {len(chunks)} chunks from {path.name}")
            
            if not self.chunks:
                print("❌ No chunks loaded!")
                return False
            
            print(f"✓ Total chunks loaded: {len(self.chunks)}")
            return True
        except Exception as e:
            print(f"❌ Error loading chunks: {e}")
            return False
    
    def generate_embeddings(self, batch_size: int = 32) -> bool:
        """Generate embeddings for all chunks."""
        try:
            print("\n[2/4] Generating embeddings with PhoBERT...")
            
            # Extract texts for embedding (use context-hoisted version)
            texts_to_embed = [chunk['text_for_embedding'] for chunk in self.chunks]
            
            start_time = time.time()
            self.embeddings = get_embeddings(texts_to_embed, batch_size=batch_size)
            elapsed = time.time() - start_time
            
            if self.embeddings is None or len(self.embeddings) == 0:
                print("❌ Failed to generate embeddings")
                return False
            
            print(f"✓ Generated embeddings for {len(self.embeddings)} chunks in {elapsed:.2f}s")
            print(f"  Embedding dimension: {self.embeddings.shape[1]}")
            return True
        except Exception as e:
            print(f"❌ Error generating embeddings: {e}")
            import traceback
            traceback.print_exc()
            return False
    
    def build_faiss_index(self) -> bool:
        """Build FAISS index from embeddings."""
        try:
            print("\n[3/4] Building FAISS index...")
            
            # Use L2 distance metric (Euclidean)
            dimension = self.embeddings.shape[1]
            self.faiss_index = faiss.IndexFlatL2(dimension)
            
            # Add vectors to index
            self.faiss_index.add(self.embeddings.astype(np.float32))
            
            print(f"✓ Built FAISS index with {self.faiss_index.ntotal} vectors")
            print(f"  Index type: IndexFlatL2")
            print(f"  Dimension: {dimension}")
            
            return True
        except Exception as e:
            print(f"❌ Error building FAISS index: {e}")
            return False
    
    def prepare_corpus_entries(self) -> bool:
        """Prepare corpus entries for storage."""
        try:
            print("\n[4/4] Preparing corpus entries...")
            
            self.corpus_entries = []
            
            for idx, chunk in enumerate(self.chunks):
                entry = {
                    'id': idx,
                    'chunk_id': chunk['id'],
                    'text': chunk['text_original'],
                    'text_for_display': chunk['text_for_embedding'],  # Full context-hoisted text
                    'source': chunk['metadata'].get('law_source', 'Unknown'),
                    'metadata': chunk['metadata'],
                }
                self.corpus_entries.append(entry)
            
            print(f"✓ Prepared {len(self.corpus_entries)} corpus entries")
            return True
        except Exception as e:
            print(f"❌ Error preparing corpus: {e}")
            return False
    
    def save_index_and_corpus(self) -> bool:
        """Save FAISS index and corpus data to disk."""
        try:
            print("\nSaving to disk...")
            
            # Save FAISS index
            faiss.write_index(self.faiss_index, str(self.faiss_index_path))
            print(f"✓ Saved FAISS index to {self.faiss_index_path}")
            
            # Save corpus data
            corpus_data = {
                'total_entries': len(self.corpus_entries),
                'data': self.corpus_entries,
            }
            with open(self.corpus_path, 'w', encoding='utf-8') as f:
                json.dump(corpus_data, f, ensure_ascii=False, indent=2)
            print(f"✓ Saved corpus data to {self.corpus_path}")
            
            # Save manifest (metadata about the index)
            manifest = {
                'version': '2.0',
                'timestamp': time.time(),
                'total_chunks': len(self.chunks),
                'embedding_dimension': self.embeddings.shape[1],
                'faiss_index_path': str(self.faiss_index_path),
                'corpus_path': str(self.corpus_path),
                'chunk_sources': list(set(c['metadata'].get('law_source', 'Unknown') 
                                         for c in self.chunks)),
                'vehicle_types': self._get_vehicle_type_distribution(),
                'with_metadata': {
                    'vehicle_type': sum(1 for c in self.chunks 
                                       if c['metadata'].get('vehicle_type')),
                    'penalty_range': sum(1 for c in self.chunks 
                                        if c['metadata'].get('penalty_range')),
                    'points_deducted': sum(1 for c in self.chunks 
                                          if c['metadata'].get('points_deducted')),
                    'references': sum(1 for c in self.chunks 
                                     if c['metadata'].get('references')),
                }
            }
            with open(self.manifest_path, 'w', encoding='utf-8') as f:
                json.dump(manifest, f, ensure_ascii=False, indent=2)
            print(f"✓ Saved manifest to {self.manifest_path}")
            
            return True
        except Exception as e:
            print(f"❌ Error saving to disk: {e}")
            return False
    
    def _get_vehicle_type_distribution(self) -> Dict[str, int]:
        """Get distribution of vehicle types across chunks."""
        dist = {}
        for chunk in self.chunks:
            vtype = chunk['metadata'].get('vehicle_type')
            if vtype:
                dist[vtype] = dist.get(vtype, 0) + 1
        return dist
    
    def print_statistics(self):
        """Print build statistics."""
        print("\n" + "="*80)
        print("VECTOR DATABASE BUILD STATISTICS")
        print("="*80)
        print(f"Total chunks: {len(self.chunks)}")
        print(f"Embedding dimension: {self.embeddings.shape[1]}")
        print(f"FAISS index type: IndexFlatL2")
        print(f"Index size: {self.faiss_index.ntotal} vectors")
        
        # Vehicle type distribution
        vtype_dist = self._get_vehicle_type_distribution()
        if vtype_dist:
            print(f"\nVehicle type distribution:")
            for vtype, count in sorted(vtype_dist.items()):
                print(f"  - {vtype}: {count} chunks")
        
        # Metadata distribution
        print(f"\nMetadata coverage:")
        print(f"  - With vehicle_type: {sum(1 for c in self.chunks if c['metadata'].get('vehicle_type'))}")
        print(f"  - With penalty_range: {sum(1 for c in self.chunks if c['metadata'].get('penalty_range'))}")
        print(f"  - With points_deducted: {sum(1 for c in self.chunks if c['metadata'].get('points_deducted'))}")
        print(f"  - With references: {sum(1 for c in self.chunks if c['metadata'].get('references'))}")
        
        # Law sources
        sources = {}
        for chunk in self.chunks:
            src = chunk['metadata'].get('law_source', 'Unknown')
            sources[src] = sources.get(src, 0) + 1
        print(f"\nLaw sources:")
        for src, count in sources.items():
            print(f"  - {src}: {count} chunks")
        
        print("="*80)


def main():
    """Main entry point."""
    print("\n" + "="*80)
    print("BUILDING VECTOR DATABASE FROM PIPELINE CHUNKS")
    print("="*80)
    
    builder = VectorDatabaseBuilder(output_dir='vector_store')
    
    # Load chunks from pipeline
    chunk_files = [
        'data/processed/luật_35_chunks.json',
        'data/processed/nd168_chunks.json',
        'data/processed/luat_36_chunks.json',
    ]
    
    if not builder.load_chunks_from_pipeline(chunk_files):
        sys.exit(1)
    
    # Generate embeddings
    if not builder.generate_embeddings(batch_size=32):
        sys.exit(1)
    
    # Build FAISS index
    if not builder.build_faiss_index():
        sys.exit(1)
    
    # Prepare corpus
    if not builder.prepare_corpus_entries():
        sys.exit(1)
    
    # Save to disk
    if not builder.save_index_and_corpus():
        sys.exit(1)
    
    # Print statistics
    builder.print_statistics()
    
    print("\n✅ Vector database successfully built!")
    print(f"Index: {builder.faiss_index_path}")
    print(f"Corpus: {builder.corpus_path}")
    print(f"Manifest: {builder.manifest_path}")
    print()


if __name__ == '__main__':
    main()
